version: "3.7"

services:
  postgres:
    container_name: posts-db
    image: postgres
    hostname: localhost
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    restart: unless-stopped
